### ISSUE TITLE
Source code should not contain TODO comments 

### ISSUE THREAD

**Issue by jmolivas** [terra-ops/terra-cli#49]
- [ ] in src/terra/Command/App/AppRemove.php, line 60
- [ ] in src/terra/Command/Environment/EnvironmentRemove.php, line 88
- [ ] in src/terra/Command/Environment/EnvironmentTest.php, line 93
- [ ] in src/terra/Command/Status.php, line 132
- [ ] in src/terra/Factory/EnvironmentFactory.php, line 228
- [ ] in src/terra/Factory/EnvironmentFactory.php, line 229
- [ ] in src/terra/Factory/EnvironmentFactory.php, line 267
- [ ] in src/terra/Factory/EnvironmentFactory.php, line 428

**Comment by jonpugh** [comment]
I'm going to close this as "won't fix" for now, as we are still so early in the project I need those TODOs to remind myself of what work we need to do.

Let's be sure to remove them before a release, though.

Thanks, @jmolivas !
