### ISSUE TITLE
[STORY] Domain Names

### ISSUE THREAD

**Issue by jonpugh** [terra-ops/terra-cli#9]
**As a** web developer
**I want to** be able to map domain names to environments.
**So that I** don't have to remember IP addresses and ports.
- [ ] #20 Ensure the URL proxy container is running when displaying URLs for environments.
- [ ] #19 Make Environment DNS setup automatic
- [ ] #18 Allow adding of domains to environments
